AWSTemplateFormatVersion: "2010-09-09"
Description: "This template creates security group for WordPress and RDS"

Resources:
  SecurityGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for EC2 instance on WordPress"
      VpcId: !ImportValue MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: securitygroup1


  SecurityGroup2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for EC2 instance on RDS"
      VpcId: !ImportValue  MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: "10.0.0.1/25"
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: "10.0.0.1/25"
      Tags:
        - Key: Name
          Value: securitygroup2
Outputs:
  SecurityGroup2:
    Value: !Ref SecurityGroup2
    Export:
       Name: SecurityGroup2

  SecurityGroup1:
    Value: !Ref SecurityGroup1
    Export:
       Name: SecurityGroup1

###Has been decommissioned and deleted from AWS CloudFormation service###
